services:
  vitepress:
    container_name: documentation-documentation
    build:
      context: .
      target: 'develop-stage'
    ports:
      - "5173:5173"  # Map the port used by the VitePress development server
    volumes:
      - ./app:/app
    command: /bin/sh -c "npm install && npm run docs:dev --host"
